# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.5 # Use the latest stable version of clang-format
    hooks:
      - id: clang-format
        args: ["--style=file", "-i"] # --style=file tells clang-format to look for .clang-format
        files: '\.(c|cc|cpp|cxx|h|hh|hpp|hxx|m|mm)$'
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use a recent stable version
    hooks:
      - id: black
        additional_dependencies: ["black[jupyter]"]
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1 # Use a recent stable version from the official repo
    hooks:
      - id: isort