repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.7
    hooks:
      - id: clang-format
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        additional_dependencies: ["black[jupyter]"]
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort